"""initial_schema

Revision ID: 8c92d401d296
Revises: 
Create Date: 2026-05-20 13:02:55.386463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c92d401d296'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('zones_ibfk_1'), 'zones', type_='foreignkey')
    op.create_foreign_key(None, 'zones', 'cameras', ['camera_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zones', type_='foreignkey')
    op.create_foreign_key(op.f('zones_ibfk_1'), 'zones', 'cameras', ['camera_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
